
KEYWORDS = [
'action',
'always',
'any_errors_fatal',
'args',
'async',
'become',
'become_flags',
'become_method',
'become_user',
'block',
'changed_when',
'check_mode',
'collections',
'connection',
'debugger',
'delay',
'delegate_facts',
'delegate_to',
'diff',
'environment',
'fact_path',
'failed_when',
'force_handlers',
'gather_facts',
'gather_subset',
'gather_timeout',
'handlers',
'hosts',
'ignore_errors',
'ignore_unreachable',
'local_action',
'loop',
'loop_control',
'max_fail_percentage',
'module_defaults',
'name',
'no_log',
'notify',
'order',
'poll',
'port',
'post_tasks',
'pre_tasks',
'register',
'remote_user',
'rescue',
'retries',
'roles',
'run_once',
'serial',
'strategy',
'tags',
'tasks',
'until',
'vars',
'vars_files',
'vars_prompt',
'when'
]

DEPRECATED_KEYWORDS = [
'accelerate',
'accelerate_ipv6',
'accelerate_port',
'always_run',
'args'    
]


# ==================================================================================== PER ELEMENT

DEPRECATED_PLAY_KEYWORDS = [
'accelerate',
'accelerate_ipv6',
'accelerate_port',
'always_run'
]

DEPRECATED_ROLE_KEYWORDS = [
'always_run'
]

DEPRECATED_BLOCK_KEYWORDS = [
'always_run'
]

DEPRECATED_TASK_KEYWORDS = [
'always_run',
'args'
]


PLAY_KEYWORDS = [# Ansible keywords for play (https://docs.ansible.com/ansible/latest/reference_appendices/playbooks_keywords.html?highlight=play#play)
'any_errors_fatal',
'become',
'become_flags',
'become_method',
'become_user',
'check_mode',
'collections',
'connection',
'debugger',
'diff',
'environment',
'fact_path',
'force_handlers',
'gather_facts',
'gather_subset',
'gather_timeout',
'handlers',
'hosts',
'ignore_errors',
'ignore_unreachable',
'max_fail_percentage',
'module_defaults',
'name',
'no_log',
'order',
'port',
'post_tasks',
'pre_tasks',
'remote_user',
'roles',
'run_once',
'serial',
'strategy',
'tags',
'tasks',
'vars',
'vars_files',
'vars_prompt'
]

ROLE_KEYWORDS = [# Ansible keywords for role (https://docs.ansible.com/ansible/latest/reference_appendices/playbooks_keywords.html?highlight=play#role)
'any_errors_fatal',
'become',
'become_flags',
'become_method',
'become_user',
'check_mode',
'collections',
'connection',
'debugger',
'delegate_facts',
'delegate_to',
'diff',
'environment',
'ignore_errors',
'ignore_unreachable',
'module_defaults',
'name',
'no_log',
'port',
'remote_user',
'run_once',
'tags',
'vars',
'when'
]

BLOCK_KEYWORDS = [# Ansible keywords for block (https://docs.ansible.com/ansible/latest/reference_appendices/playbooks_keywords.html?highlight=play#block)
'always',
'any_errors_fatal',
'become',
'become_flags',
'become_method',
'become_user',
'block',
'check_mode',
'collections',
'connection',
'debugger',
'delegate_facts',
'delegate_to',
'diff',
'environment',
'ignore_errors',
'ignore_unreachable',
'module_defaults',
'name',
'no_log',
'port',
'remote_user',
'rescue',
'run_once',
'tags',
'vars',
'when'
]

TASK_KEYWORDS = [#  Ansible keywords for task (https://docs.ansible.com/ansible/latest/reference_appendices/playbooks_keywords.html?highlight=play#task)
'action',
'any_errors_fatal',
'args',
'async',
'become',
'become_flags',
'become_method',
'become_user',
'changed_when',
'check_mode',
'collections',
'connection',
'debugger',
'delay',
'delegate_facts',
'delegate_to',
'diff',
'environment',
'failed_when',
'ignore_errors',
'ignore_unreachable',
'local_action',
'loop',
'loop_control',
'module_defaults',
'name',
'no_log',
'notify',
'poll',
'port',
'register',
'remote_user',
'retries',
'run_once',
'tags',
'until',
'vars',
'when'
#'with_<lookup_plugin>' TODO support 
]
